name: landslide_fe
description: "Landslide application work with landslide system, designed by Quyet Thanh"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  mqtt_client: ^10.0.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
